
[spawning]
    moth_count = 15.0
    spawn_probability = 13.0

    [spawning.spawn_distances]
        x_spawn_distance = 30
        z_spawn_distance = 30
        y_spawn_distance = 30

    [spawning.height_limits]
        neg_height = -10
        pos_height = 192

[general]
    glowing_moths = false
    spawn_moths = true

    [general.movement_config]
        y_velocity = 100.0
        specific_velocities = true
        z_velocity = 100.0
        x_velocity = 100.0

[block_spawning]
    z_block_spawn_distance = 3
    spawn_by_blocks = true
    x_block_spawn_distance = 3
    y_block_spawn_distance = 3
    setBlockSpawnProbablity = 15.0

[block_spawning.allowed_blocks]
    redstone_torches = true
    candles = true
    torches = true
    redstone_lamps = true
    lanterns = true

